import os
import logging

GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')
GITHUB_ORG = os.getenv('GITHUB_ORG') or ""
GITHUB_REPONAME = os.getenv('GITHUB_REPONAME')

ENABLE_TRACE_LOGGING = os.getenv('ENABLE_TRACE_LOGGING', 'true').lower() == 'true'
LOG_LEVEL = logging.DEBUG
HOST_ADDRESS = os.getenv('HOST_ADDRESS', "localhost:50052")
APPLICATION_INSIGHTS_CONNECTION_STRING = os.getenv('APPLICATION_INSIGHTS_CONNECTION_STRING')

AZURE_OPENAI_CHAT_DEPLOYMENT_NAME = os.getenv('AZURE_OPENAI_CHAT_DEPLOYMENT_NAME', "gpt-4o")

AZURE_OPENAI_API_KEY= os.getenv('AZURE_OPENAI_API_KEY')
AZURE_OPENAI_ENDPOINT=os.getenv('AZURE_OPENAI_ENDPOINT')
OPENAI_API_VERSION=os.getenv('OPENAI_API_VERSION', '2024-08-01-preview')
AZURE_OPENAI_API_VERSION = os.getenv('AZURE_OPENAI_API_VERSION', '2024-08-01-preview')
